New OmeroImageReader: try to create an op that is creating a connection and loading a single image from omero without any GUI element involved
Problem: 
java.lang.IllegalArgumentException: Required service is missing:
net.imagej.omero.OMEROService
Context: org.scijava.Context@3e9803c2
ClassLoader: sun.misc.Launcher$AppClassLoader@4e0e2f2a